# Generated by Django 4.2.29 on 2026-04-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_notes_to_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='alerts',
            field=models.TextField(blank=True, verbose_name='Alerts'),
        ),
    ]
