# Generated by Django 4.2.29 on 2026-03-18 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MileageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('start_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('end_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('end_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mileageentry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uniq_mileage_user_date'),
        ),
    ]
