# Generated by Django 4.2.29 on 2026-03-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mileageentry',
            name='uniq_mileage_user_date',
        ),
    ]
