# Generated by Django 4.2.29 on 2026-04-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_remove_mileageentry_uniq_mileage_user_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mileageentry',
            options={'ordering': ['-date', '-start_mileage', '-id']},
        ),
    ]
